container:
    image: ubuntu:latest
    cpu: 8
    memory: 8

env:
    CIRRUS_CLONE_DEPTH: 100

build_kernel_task:
  name: Build Kernel
  install_script: |
    apt update -y
    apt install -y rsync gcc-arm-linux-gnueabi binutils make python3 libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs libxml2
    ln -s /usr/bin/python3 /usr/bin/python
    git clone https://github.com/tiann/KernelSU.git
    git clone https://gerrit.googlesource.com/git-repo
    mkdir android-kernel && cd android-kernel
    ../git-repo/repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-android13-5.15-2023-06
    ../git-repo/repo sync -j$(nproc --all)
    echo "[+] KernelSU setup"
    GKI_ROOT=$(pwd)
    echo "[+] GKI_ROOT: $GKI_ROOT"
    echo "[+] Copy kernel su driver to $GKI_ROOT/common/drivers"
    cp -r ../qaq $GKI_ROOT/common/drivers/qaq
    cp -r ../KernelSU/kernel $GKI_ROOT/common/drivers/kernelsu
    echo "[+] Add kernel su driver to Makefile"
    DRIVER_MAKEFILE=$GKI_ROOT/common/drivers/Makefile
    echo "obj-y += qaq/" >> $DRIVER_MAKEFILE
    grep -q "kernelsu" $DRIVER_MAKEFILE || echo "obj-y += kernelsu/" >> $DRIVER_MAKEFILE
    echo "[+] KernelSU setup Done."
    cd -

  start_build_script: |
    cd android-kernel
    BUILD_BOOT_IMG=1 SKIP_VENDOR_BOOT=1 KERNEL_BINARY=Image AVB_SIGN_BOOT_IMG=1 AVB_BOOT_PARTITION_SIZE=$((64*1024*1024)) AVB_BOOT_ALGORITHM=SHA256_RSA2048 AVB_BOOT_KEY=prebuilts/kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem BOOT_IMAGE_HEADER_VERSION=4 LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
    cd -

  output_artifacts:
    path: "./android-kernel/out/*/dist/Image"
  