name: Build gki ko
on:
  workflow_dispatch:
    inputs:
      TAG:
        required: true
        default: "android13-5.15-2023-05"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
    steps:
    - uses: actions/checkout@v3
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.event.inputs.TAG }}
        append-timestamp: false
    - name: Download Kernel Source
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://gerrit.googlesource.com/git-repo
        mkdir android-kernel && cd android-kernel
        ../git-repo/repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-${{ github.event.inputs.TAG }}
        ../git-repo/repo sync -j$(nproc --all)
        echo "[+] drivers setup"
        GKI_ROOT=$(pwd)
        echo "[+] GKI_ROOT: $GKI_ROOT"
        echo "[+] Copy kernel hack driver to $GKI_ROOT/common/drivers"
        ln -sf $GITHUB_WORKSPACE/qaq $GKI_ROOT/common/drivers/qaq
        echo "[+] Add kernel hack driver to Makefile"
        DRIVER_MAKEFILE=$GKI_ROOT/common/drivers/Makefile
        echo "obj-y += qaq/" >> $DRIVER_MAKEFILE
        mv $GITHUB_WORKSPACE/qaq/Makefile1 $GKI_ROOT/common/drivers/qaq/Makefile
        mv $GITHUB_WORKSPACE/qaq/memory.c.bak $GKI_ROOT/common/drivers/qaq/memory.c
        echo "[+] drivers setup Done."
        cd -
    - name: Build Boot
      working-directory: android-kernel
      env:
        ktag: ${{ github.event.inputs.TAG }}
        chatid: ${{ secrets.TELEGRAM_CHAT_ID }}
        bottoken: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        $GITHUB_WORKSPACE/listen.sh qaq.ko & echo 666
        CCACHE="/usr/bin/ccache" LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
