name: Test
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Run Test by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        gold -v