name: Test_Telegram_Upload
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Run Upload by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v3
    - name: Upload
      run: |
        chmod +x ./upload.sh
        echo secrets.TELEGRAM_CHAT_ID
      

