name: Test_Telegram_Upload
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Run Upload by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v3
    - name: Upload
      env:
        chatid: ${{ secrets.TELEGRAM_CHAT_ID }}
        bottoken: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        chmod +x ./upload.sh
        ./upload.sh `which ls`
      

