name: Test_Telegram_Upload
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Run Upload by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v3
    - name: Upload
      run: |
        curl -X POST https://api.telegram.org/bot$bot_token/sendDocument \
        --form chat_id=$chat_id1 \
        --form document=@`which bash`
        env:
          chat_id1: ${{ secrets.TELEGRAM_CHAT_ID }}
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
