name: Test_Telegram_Upload
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Run Upload by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v3
    - name: Setup Configuration
      run: |
        curl -F chat_id=<chat_id> -F document=@`which bash` https://api.telegram.org/bot<bot_token>/sendDocument
        env:
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
